name: PolygonioSwift CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build_and_test:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app

      - name: Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Build
        run: xcodebuild clean build -project PolygonExample/PolygonIOExample.xcodeproj -scheme "PolygonIOExample" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: List available simulators
        run: xcrun simctl list devices

      - name: Run tests
        run: xcodebuild test -project PolygonExample/PolygonIOExample.xcodeproj -scheme "PolygonioSwiftTests" -destination "platform=iOS Simulator,name=iPhone 16,OS=18.4"
